from gym_minigrid.envs.empty import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.obstructedmaze import *
from gym_minigrid.envs.fourrooms import *
from gym_minigrid.envs.dynamicobstacles import *
from gym_minigrid.envs.collect_game import *